name: sangam
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: 
  cloud_firestore: 
  cupertino_icons: ^1.0.3
  curved_navigation_bar: 
  firebase_auth: 
  firebase_core: 
  flutter_icons: 
  flutter_svg: 
  font_awesome_flutter: 
  flutter_login_facebook:
  get: 
  google_sign_in: 
  http: 
  mockito:
  page_transition:
  email_validator: 

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^1.11.0
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/songs/
    - assets/

  fonts:
    - family: Comforta
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
