name: sangam
description: A Clean Ui of Music Streamig App [Sangam].

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cloud_firestore: any
  curved_navigation_bar: any
  device_preview: any
  email_validator: any
  equatable: ^2.0.5
  firebase_auth: any
  firebase_core: any
  firebase_storage: any
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_sound: any
  flutter_svg: any
  font_awesome_flutter: any
  get: any
  get_it: ^7.6.0
  google_fonts: any
  google_sign_in: any
  http: any
  injectable: ^2.3.0
  lottie: any
  package_info: ^2.0.2
  provider: any
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/Sangam.png
    - assets/images/
    - assets/
