name: sangam
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.19.0
  cupertino_icons: ^1.0.3
  curved_navigation_bar: ^0.3.7
  flutter_icons: ^1.1.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0
  http: ^0.13.3
  page_transition: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/songs/
    - assets/

  fonts:
    - family: Comforta
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
