name: sangam
description: A Clean Ui of Music Streamig App [Sangam].

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  cupertino_icons: ^1.0.2
  firebase_auth:
  firebase_core:
  flutter_login_facebook:
  get:
  google_sign_in:
  http:
  email_validator:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/Sangam.png

  fonts:
    - family: Comforta
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
