
# name: sangam
# description: A new Flutter project.

# publish_to: "none"

# version: 1.0.0+1

# environment:
#   sdk: ">=2.7.0 <3.0.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   audioplayers: ^0.19.0
#   cloud_firestore: ^2.2.0
#   cupertino_icons: ^1.0.3
#   curved_navigation_bar: ^0.3.7
#   firebase_auth: ^1.2.0
#   firebase_core: ^1.2.0
#   flutter_icons: ^1.1.0
#   flutter_svg: ^0.22.0
#   font_awesome_flutter: ^9.0.0
#   google_sign_in: ^5.0.4
#   http: ^0.13.3
#   page_transition: ^2.0.2
#   provider: ^5.0.0

# dev_dependencies:
#   integration_test:
#     sdk: flutter
#   flutter_driver:
#     sdk: flutter
#   flutter_test:
#     sdk: flutter
#   mockito:
#   test: any

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/images/
#     - assets/icons/
#     - assets/songs/
#     - assets/

#   fonts:
#     - family: Comforta
#       fonts:
#         - asset: fonts/Comfortaa-Regular.ttf
#         - asset: fonts/Comfortaa-Bold.ttf
#           weight: 700

name: sangam
description: A Clean Ui of Music Streamig App [Sangam].

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.3.0
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  flutter_login_facebook: ^1.0.1
  flutter_sound: ^8.3.4
  get: ^4.1.4
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.4
  http: ^0.13.3
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 

flutter:
  uses-material-design: true
  assets:
    - assets/Sangam.png

