name: sangam
description: A Clean Ui of Music Streamig App [Sangam].

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  cloud_firestore: ^3.4.8
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  device_preview: ^1.1.0
  email_validator: ^2.0.1
  firebase_auth: ^3.9.0
  firebase_core: ^1.3.0
  firebase_storage: ^10.3.9
  flutter:
    sdk: flutter
  flutter_login_facebook: ^1.0.1
  flutter_sound: ^9.2.13
  flutter_svg: ^1.1.5
  font_awesome_flutter: ^10.2.1
  get: ^4.1.4
  google_fonts: ^3.0.1
  google_sign_in: ^5.0.4
  http: ^0.13.3
  lottie: ^1.4.3
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/Sangam.png
    - assets/images/
