name: sangam
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.1.3
  flutter_bloc: ^7.0.0
  flutter_icons: ^1.1.0
  flutter_svg: ^0.22.0
  get: ^4.1.4
  google_fonts: ^2.0.0
  line_icons: ^2.0.1
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
  # fonts:
    # - family: RobotoMono
    #   fonts:
    #     - asset: fonts/RobotoMono-Regular.ttf
    #     - asset: fonts/RobotoMono-Bold.ttf
    #       weight: 700
    # - family: Comforta
    #   fonts:
    #     - asset: fonts/Comforta-Regular.ttf
    #     - asset: fonts/Comforta-Bold.ttf
    #       weight: 700
          
    

