// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM22aNUk5IBZqcOUrTDZyBmqV3lEMnRjA',
    appId: '1:183105071757:web:4af49ce45ec27f8bb650c4',
    messagingSenderId: '183105071757',
    projectId: 'sangam-music',
    authDomain: 'sangam-music.firebaseapp.com',
    databaseURL: 'https://sangam-music-default-rtdb.firebaseio.com',
    storageBucket: 'sangam-music.appspot.com',
    measurementId: 'G-VNRFWMJEW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGcm0TKY1LX_vsAHoPIdHdl_RqWL8FsFc',
    appId: '1:183105071757:android:194865cca0c387d5b650c4',
    messagingSenderId: '183105071757',
    projectId: 'sangam-music',
    databaseURL: 'https://sangam-music-default-rtdb.firebaseio.com',
    storageBucket: 'sangam-music.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASyINbrKQ3HLMkdPfh7I_pDaFIoBdQzsk',
    appId: '1:183105071757:ios:eaa185cbeff8fbb4b650c4',
    messagingSenderId: '183105071757',
    projectId: 'sangam-music',
    databaseURL: 'https://sangam-music-default-rtdb.firebaseio.com',
    storageBucket: 'sangam-music.appspot.com',
    androidClientId:
        '183105071757-tbq7gql7idf5dib1c8vq84h46kn89qg9.apps.googleusercontent.com',
    iosClientId:
        '183105071757-6d07ao3gs7t8h1smc9el1ncaks9l0egr.apps.googleusercontent.com',
    iosBundleId: 'com.example.sangam',
  );
}
